USE master;
GO

CREATE LOGIN [new] WITH PASSWORD = '1234', CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF;
GO
ALTER SERVER ROLE sysadmin ADD MEMBER [new];
GO

CREATE DATABASE LibraryDB;
GO
USE LibraryDB;
GO
CREATE TABLE users (
    id INT PRIMARY KEY IDENTITY(1,1),
    userId VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(50) NOT NULL,
    role VARCHAR(20) NOT NULL 
);

