USE master;
GO

CREATE LOGIN [new] WITH PASSWORD = '1234', CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF;
GO
USE LibraryDB;
CREATE USER [new] FOR LOGIN [new];
ALTER ROLE db_owner ADD MEMBER [new];
GO

CREATE DATABASE LibraryDB;
GO
USE LibraryDB;
GO
CREATE TABLE users (
    id INT PRIMARY KEY IDENTITY(1,1),
    userId VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(50) NOT NULL,
    role VARCHAR(20) NOT NULL 
);
GO
ALTER TABLE users
ALTER COLUMN password VARCHAR(255) NOT NULL;
GO
ALTER TABLE users
ADD email VARCHAR(100) UNIQUE NOT NULL;
GO


ALTER TABLE users
ADD reset_token VARCHAR(255) NULL;
GO
ALTER TABLE users
ADD token_expire DATETIME NULL;
GO
